### ISSUE TITLE
Issue with petfinder API client `Uncaught SyntaxError: Unexpected token <`

### ISSUE THREAD

**Issue by drupalastic** [btholt/complete-intro-to-react-v4#13]
@btholt  Console gives following Error:

```
Uncaught SyntaxError: Unexpected token <
```

After these lines of code executes:
```
  componentDidMount() {
    petfinder.breed.list({ animal: "dog" }).then(console.log, console.error);
  }
```

Regarding : https://frontendmasters.com/courses/complete-react-v4/using-the-petfinder-api-client/

**Comment by drupalastic** [comment]
Looks like, it's working now. Thanks!!

**Comment by djviy** [comment]
> Looks like, it's working now. Thanks!!

What did you do to resolve the issue?

**Comment by drupalastic** [comment]
> > Looks like, it's working now. Thanks!!
> 
> What did you do to resolve the issue?

I think I restarted the server. In the terminal ctrl+c to stop it then Yarn+start to re-run it...

**Comment by 1Marc** [comment]
There's a more thorough explanation of how to debug here: https://github.com/btholt/complete-intro-to-react-v4/issues/3#issuecomment-425124265
