### ISSUE TITLE
on running the project i am unable to select a breed from dropdown

### ISSUE THREAD

**Issue by ibolton336** [btholt/complete-intro-to-react-v4#2]
I think this is a cors issue but could be worth noting in readme. Thanks for the great walk through.

**Comment by mmhuntsberry** [comment]
I had an issue similar.  In the actionCreator folder in changeBreed, the return type is `SET_BREED`.  Should be `CHANGE_BREED`.  Once changed, worked correctly.  Hope that helps.

**Comment by 1Marc** [comment]
Perhaps this issue is helpful? https://github.com/btholt/complete-intro-to-react-v4/issues/3

Closing this issue unless you can give us some code or a way to look into resolving this for you...
