### ISSUE TITLE
import pf from petfinder-client

### ISSUE THREAD

**Issue by winniethefoo** [btholt/complete-intro-to-react-v4#21]
Can you explain where the method pf is defined as I believe I don't really understand import?

**Comment by 1Marc** [comment]
`pf` comes from the [Pet Finder API module](https://github.com/btholt/petfinder-client) which is installed when you add the package to your package.json and run `npm install`.

**Comment by winniethefoo** [comment]
Can pf be any name or is it specific? I don't see pf defined in the Pet Finder API module. How do I know what to import when using someone elses API if its not documented?

**Comment by 1Marc** [comment]
Yes you can name it anything you want. The documentation is the Typescript definitions https://github.com/btholt/petfinder-client/blob/master/index.d.ts

**Comment by 1Marc** [comment]
Good tip. Time permitting I can add info about module imports. @winniethefoo
