### ISSUE TITLE
Getting CORS errors accessing Petfinder API

### ISSUE THREAD

**Issue by the-nick-wilson** [btholt/complete-intro-to-react-v4#29]
I'm getting the following error all of a sudden from the browser when running this project: 

> Cross-Origin Read Blocking (CORB) blocked cross-origin response http://api.petfinder.com/pet.find?key=undefined&format=json&location=Seattle%2C%20WA&animal=&breed=&output=full&callback=jsonp_03yl8az6ytcuukf with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Did something change on the Petfinder API server?

**Comment by 1Marc** [comment]
Duplicate issue #9

**Comment by the-nick-wilson** [comment]
Yep, clearing the cache helped, thank you!
