### ISSUE TITLE
SyntaxError: expected expression, got '<'[Learn More] breed.list:1

### ISSUE THREAD

**Issue by cacheUp** [btholt/complete-intro-to-react-v4#3]
SyntaxError: expected expression, got '<'[Learn More] breed.list:1

<img width="2048" alt="screen shot 2018-09-25 at 12 36 53 am" src="https://user-images.githubusercontent.com/42074251/45980710-65f65700-c05b-11e8-9f2f-ec565910a029.png">

I'm not seeing the object in my console instead this error pops up.

**Comment by sorband** [comment]
Hello, I get the same error in Firefox. Chrome says it's a CORB issue:

> jsonp.js:67 Cross-Origin Read Blocking (CORB) blocked cross-origin response http://api.petfinder.com/pet.find?key=undefined&format=json&location=Seattle%2C%20WA&output=full&callback=jsonp_2vyr291vjltp984 with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

I'm running this under W10 WSL. I tried cloning the repo at the specified commit and I am getting the same error.

**Comment by laniehei** [comment]
@cacheUp you're getting an error related to babel. It's not interpreting the JSX correctly. Please check your files against Brian's. 

Have both of you run `npm install`?

**Comment by sorband** [comment]
@laniehei yep, still the same. As I said above, I get the same error even in this actual repo at the 89678fe commit.

**Comment by cacheUp** [comment]
@laniehei @sorband @btholt  i think its something with petfinder-client. Later in the video he reconfigures babel, so its not that. I even went back to the beginning and re-followed along with everything. Also changed dev dependencies to the versions he was using.

**Comment by 1Marc** [comment]
I thought I remembered Brian fixing this in the course by clearing out the Parcel cache with `rm -rf .cache`

**Comment by 1Marc** [comment]
Just verified this.

If you receive the `SyntaxError: Unexpected token '<'` error, then that means your `.env` file with the Petfinder API keys was not found by Parcel. This happens if you run `npm run dev` before adding the `.env` file.

To fix this error, you need to clear Parcel's cache with running `rm -rf .cache` ... then make sure you have created a `.env` file in your root directly with `API_KEY=` and `API_SECRET=` from the Petfinder API and the error will resolve.

**Comment by cacheUp** [comment]
ahhhhhhh yes thank you so much @1Marc also thank you @btholt for the best react walkthrough. Love front end masters !!

**Comment by scottcate** [comment]
I added this to my package.json, it's something I run when weird things happen. Just a reminder to myself that a bundler is in the middle of my code and the browser.

`
    "dev": "parcel src/index.html",
    "dev-clear": "rm -rf .cache && parcel src/index.html",`

**Comment by cacheUp** [comment]
@scottcate so then I would npm run dev-clear and it will clear my cache for me?

**Comment by scottcate** [comment]
> @scottcate so then I would npm run dev-clear and it will clear my cache for me?

Yes, but as you can imagine the build is much slower, so that's what I did it as a second run script.

**Comment by djviy** [comment]
> Just verified this.
> 
> If you receive the `SyntaxError: Unexpected token '<'` error, then that means your `.env` file with the Petfinder API keys was not found by Parcel. This happens if you run `npm run dev` before adding the `.env` file.
> 
> To fix this error, you need to clear Parcel's cache with running `rm -rf .cache` ... then make sure you have created a `.env` file in your root directly with `API_KEY=` and `API_SECRET=` from the Petfinder API and the error will resolve.

Thanks a lot! 👍  I use create-react-app instead of Parcel. To use variables I changed API_KEY to REACT_APP_API_KEY. 
Now _console.log(process.env)_ shows 
`[Log] {NODE_ENV: "development", PUBLIC_URL: "", REACT_APP_API_KEY: "8e5c40dbd5f82c15ca8d986f829....", REACT_APP_API_SECRET: "b787de6cd4342dfc74d622fd1ded...."}`

**Comment by ApoorvArv** [comment]
@1Marc bro, not working for me.
I deleted my cache and dist,
then created a new .env file with my API key and secret.
then ran npm run dev. Even restarted the browser
But it still is not running.

**Comment by rayjencode** [comment]
Im having an error when I try to submit. 

![screenshot](https://i.imgur.com/Y9vq4Ew.png)

**Comment by louaimabr** [comment]
someone could help me fix this error please, it's been about 5 hours since i got stuck because of that
![image](https://user-images.githubusercontent.com/64655366/86196314-e60ff180-bb4a-11ea-8b32-e99ec825ca5a.png)

**Comment by devallisamuel** [comment]
my reach router says it is unable to resolve

**Comment by devallisamuel** [comment]
my reach router says unable to resolve. can any one say why?
