### ISSUE TITLE
Issue with petfinder API not working - syntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by sweinstock** [btholt/complete-intro-to-react-v4#31]
I think my issue is different than the ones listed because it's reading the api key and the api secret, but I think the pet finder website updated their api and I only can get the keys for the new version which maybe doesn't work for this code? Is there a way to still get the old keys?

**Comment by nickwwh** [comment]
Hi, @btholt recently updated the petfinder client so that it is compatible with PetFinder API v2. However my guess is that he has not pushed the changes to npm. You can install the latest petfinder client via `npm install https://github.com/btholt/petfinder-client`

**Comment by sweinstock** [comment]
Thank you,  I ran the above in git bash and it's working perfectly now
