### ISSUE TITLE
 Configuring ESLint with React

### ISSUE THREAD

**Issue by PedrovictorSouza** [btholt/complete-intro-to-react-v4#32]
in this part of the course, i've installed the aditional linting features (npm install -D babel-eslint eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react) on my root directory (react/fem) and updated my .eslintrc.json as explained by the teacher. 

However, my app.js keeps on saying that 'Pet' is defined but never used. 

Here's my .eslintrc.json file:

{
  "extends": [
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:react/recommended",
    "plugin:jsx-a11y/recommended",
    "prettier",
    "prettier/react"
  ],
  "rules": {
    "react/jsx-uses-react": "error",
    "react/jsx-uses-vars": "error",
    "react/prop-types": 0,
    "jsx-a11y/label-has-for": 0,
    "no-console": 1
  },
  "plugins": ["react", "import", "jsx-a11y"],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  }
}

Hope you guys can help me so i can move on with the course.

Thank you.

**Comment by 1Marc** [comment]
Looks like you're on this step: https://btholt.github.io/complete-intro-to-react-v4/async-and-events-in-react/

Look at the final code: https://github.com/btholt/complete-intro-to-react-v4/commit/89678fe3f663be06f80e93370942592c03f3f5db (you can see the entire project with Browse Files)

And make sure you're using the same code and didn't miss any steps.
