### ISSUE TITLE
import react is not working

### ISSUE THREAD

**Issue by igoraccebas** [btholt/complete-intro-to-react-v4#33]
I get all these errors when importing React from "react"; and deleting React from render(React.createElement(App), document.getElementById('root'));

`react.development.js:188 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App
warningWithoutStack @ react.development.js:188
warning @ react.development.js:603
createElementWithValidation @ react.development.js:1730
render @ App.js:14
finishClassComponent @ react-dom.development.js:14695
updateClassComponent @ react-dom.development.js:14650
beginWork @ react-dom.development.js:15598
performUnitOfWork @ react-dom.development.js:19266
workLoop @ react-dom.development.js:19306
renderRoot @ react-dom.development.js:19389
performWorkOnRoot @ react-dom.development.js:20296
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
parcelRequire.App.js.react @ App.js:42
newRequire @ App.d36a57b6.js:47
(anonymous) @ App.d36a57b6.js:81
(anonymous) @ App.d36a57b6.js:120
react.development.js:188 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App
warningWithoutStack @ react.development.js:188
warning @ react.development.js:603
createElementWithValidation @ react.development.js:1730
render @ App.js:19
finishClassComponent @ react-dom.development.js:14695
updateClassComponent @ react-dom.development.js:14650
beginWork @ react-dom.development.js:15598
performUnitOfWork @ react-dom.development.js:19266
workLoop @ react-dom.development.js:19306
renderRoot @ react-dom.development.js:19389
performWorkOnRoot @ react-dom.development.js:20296
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
parcelRequire.App.js.react @ App.js:42
newRequire @ App.d36a57b6.js:47
(anonymous) @ App.d36a57b6.js:81
(anonymous) @ App.d36a57b6.js:120
react.development.js:188 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App
warningWithoutStack @ react.development.js:188
warning @ react.development.js:603
createElementWithValidation @ react.development.js:1730
render @ App.js:24
finishClassComponent @ react-dom.development.js:14695
updateClassComponent @ react-dom.development.js:14650
beginWork @ react-dom.development.js:15598
performUnitOfWork @ react-dom.development.js:19266
workLoop @ react-dom.development.js:19306
renderRoot @ react-dom.development.js:19389
performWorkOnRoot @ react-dom.development.js:20296
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
parcelRequire.App.js.react @ App.js:42
newRequire @ App.d36a57b6.js:47
(anonymous) @ App.d36a57b6.js:81
(anonymous) @ App.d36a57b6.js:120
react.development.js:188 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `App`. See https://fb.me/react-warning-keys for more information.
    in h1 (created by App)
    in App
warningWithoutStack @ react.development.js:188
warning @ react.development.js:603
validateExplicitKey @ react.development.js:1593
validateChildKeys @ react.development.js:1615
createElementWithValidation @ react.development.js:1748
render @ App.js:12
finishClassComponent @ react-dom.development.js:14695
updateClassComponent @ react-dom.development.js:14650
beginWork @ react-dom.development.js:15598
performUnitOfWork @ react-dom.development.js:19266
workLoop @ react-dom.development.js:19306
renderRoot @ react-dom.development.js:19389
performWorkOnRoot @ react-dom.development.js:20296
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
parcelRequire.App.js.react @ App.js:42
newRequire @ App.d36a57b6.js:47
(anonymous) @ App.d36a57b6.js:81
(anonymous) @ App.d36a57b6.js:120
react-dom.development.js:55 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    at invariant (http://localhost:1234/App.d36a57b6.js:3430:19)
    at createFiberFromTypeAndProps (http://localhost:1234/App.d36a57b6.js:13998:15)
    at createFiberFromElement (http://localhost:1234/App.d36a57b6.js:14018:19)
    at createChild (http://localhost:1234/App.d36a57b6.js:15818:32)
    at reconcileChildrenArray (http://localhost:1234/App.d36a57b6.js:16087:29)
    at reconcileChildFibers (http://localhost:1234/App.d36a57b6.js:16437:18)
    at reconcileChildren (http://localhost:1234/App.d36a57b6.js:18290:32)
    at updateHostComponent (http://localhost:1234/App.d36a57b6.js:18774:7)
    at beginWork (http://localhost:1234/App.d36a57b6.js:19598:18)
    at performUnitOfWork (http://localhost:1234/App.d36a57b6.js:23608:16)
invariant @ react-dom.development.js:55
createFiberFromTypeAndProps @ react-dom.development.js:10192
createFiberFromElement @ react-dom.development.js:10213
createChild @ react-dom.development.js:11979
reconcileChildrenArray @ react-dom.development.js:12230
reconcileChildFibers @ react-dom.development.js:12553
reconcileChildren @ react-dom.development.js:14356
updateHostComponent @ react-dom.development.js:14817
beginWork @ react-dom.development.js:15603
performUnitOfWork @ react-dom.development.js:19266
workLoop @ react-dom.development.js:19306
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:18532
renderRoot @ react-dom.development.js:19422
performWorkOnRoot @ react-dom.development.js:20296
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
parcelRequire.App.js.react @ App.js:42
newRequire @ App.d36a57b6.js:47
(anonymous) @ App.d36a57b6.js:81
(anonymous) @ App.d36a57b6.js:120
react-dom.development.js:17071 The above error occurred in the <div> component:
    in div (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:17071
logError @ react-dom.development.js:17107
update.callback @ react-dom.development.js:18019
callCallback @ react-dom.development.js:16387
commitUpdateEffects @ react-dom.development.js:16426
commitUpdateQueue @ react-dom.development.js:16417
commitLifeCycles @ react-dom.development.js:17337
commitAllLifeCycles @ react-dom.development.js:18690
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18902
(anonymous) @ react-dom.development.js:20372
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20371
performWorkOnRoot @ react-dom.development.js:20300
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
parcelRequire.App.js.react @ App.js:42
newRequire @ App.d36a57b6.js:47
(anonymous) @ App.d36a57b6.js:81
(anonymous) @ App.d36a57b6.js:120
react-dom.development.js:55 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    at invariant (http://localhost:1234/App.d36a57b6.js:3430:19)
    at createFiberFromTypeAndProps (http://localhost:1234/App.d36a57b6.js:13998:15)
    at createFiberFromElement (http://localhost:1234/App.d36a57b6.js:14018:19)
    at createChild (http://localhost:1234/App.d36a57b6.js:15818:32)
    at reconcileChildrenArray (http://localhost:1234/App.d36a57b6.js:16087:29)
    at reconcileChildFibers (http://localhost:1234/App.d36a57b6.js:16437:18)
    at reconcileChildren (http://localhost:1234/App.d36a57b6.js:18290:32)
    at updateHostComponent (http://localhost:1234/App.d36a57b6.js:18774:7)
    at beginWork (http://localhost:1234/App.d36a57b6.js:19598:18)
    at performUnitOfWork (http://localhost:1234/App.d36a57b6.js:23608:16)```

**Comment by 1Marc** [comment]
Did you follow the course website? https://btholt.github.io/complete-intro-to-react-v4/pure-react

You can also compare your code to the final code here: https://github.com/btholt/complete-intro-to-react-v4/commit/d6bf51f49b6c71710cd806e5e78d0c47f5dcf09a

**Comment by igoraccebas** [comment]
I redid the course and it works. I may have skipped something.

Thank you!
