### ISSUE TITLE
Problem with Api Pet 

### ISSUE THREAD

**Issue by cejodrake** [btholt/complete-intro-to-react-v4#39]
I have a problem when I get my details, do I need some authorization? 
[
![errorApiCall](https://user-images.githubusercontent.com/3629120/71460686-cd6cec00-2761-11ea-931a-37467493edec.JPG)

**Comment by 1Marc** [comment]
This course is deprecated. Please take complete intro to react v5 https://github.com/btholt/complete-intro-to-react-v5
