### ISSUE TITLE
Course Docs: First router example imports @react/router, not @reach/router

### ISSUE THREAD

**Issue by gsears** [btholt/complete-intro-to-react-v4#4]
Tiny error on the course site's [router page](https://btholt.github.io/complete-intro-to-react-v4/reach-router):

> Now we have two pages and the router available. Let's go make it ready to switch between the two.

```
// at top
import { Router } from "@react/router"; // HERE
import Details from "./Details";

// replace <Results />
<Router>
  <Results path="/" />
...
```

I imagine it should be **@reach/router.** If someone lazy (like me) copies and pastes that initial code, parcel will grab the wrong router - eek!

Thanks for the course, really enjoying it. 👍 (Given me the confidence to open my first github issue!)

**Comment by 1Marc** [comment]
Fixed! https://btholt.github.io/complete-intro-to-react-v4/reach-router

Thank you for reporting!
