### ISSUE TITLE
someone could help me fix this error please, it's been about 5 hours since i got stuck because of that

### ISSUE THREAD

**Issue by mweaber** [btholt/complete-intro-to-react-v4#42]
someone could help me fix this error please, it's been about 5 hours since i got stuck because of that
![image](https://user-images.githubusercontent.com/64655366/86196314-e60ff180-bb4a-11ea-8b32-e99ec825ca5a.png)

_Originally posted by @louaimabr in https://github.com/btholt/complete-intro-to-react-v4/issues/3#issuecomment-652150100_

**Comment by jhoe08** [comment]
the only thing I did was to remove the content on .babelsrc since the dependencies I have was already included the @babel/core and @babel/plugin-proposal-class-properties
