### ISSUE TITLE
I get "Cross-Origin Read Blocking (CORB) Blocked Origin Error" error when I try to load the page !!??

### ISSUE THREAD

**Issue by Momjo** [btholt/complete-intro-to-react-v4#9]

**Comment by imcodingideas** [comment]
You can just use firefox!

**Comment by 1Marc** [comment]
Perhaps related: https://github.com/btholt/complete-intro-to-react-v4/issues/3

Make sure you `rm -rf .cache` and make sure your API keys are in your `.env` file. Restart your browser and try it again.

**Comment by 1Marc** [comment]
There are no further details in order to debug your issue. Please provide code and screenshots or something for us to help you further debug.

**Comment by Momjo** [comment]
It worked again after I deleted .catch and reloaded browser, thanks 👍
